### ISSUE TITLE
[ Components ] 전역 사용 가능한 Alert 구현

### ISSUE THREAD

**Issue by dev-junehee** [MINI-TEAM3/admin#47]
## Todo

- [ ] Alert 컴포넌트 구현
- [ ] Recoil Atom 통해 stateAlert 구현
- [ ] 에러 처리 시 console.error 삭제 -> Alert 대체 구현
